# Project Configuration

train_label: "label_scale_mlc_bandwidth"

train_tag: "add mem features"

select_model: GroupMultiAttenResNet

if_label_scale: 1
add_mem_features: 1

train_with_all_data: 1
copy_train_model: 1
validation_data_upload_to_sql: 0


use_train_model: 0
freeze_train_model: 0
pre_trained_model_path: "../../model_history/spec_fp/mse_GroupMultiAttenResNet/GroupMultiAttenResNet.hdf5"

# train process param
K_Fold: 1
n_split: 5

# Save the fcn (0 or 1)
is_save_model: 1
save_train_data: 1
save_test_data: 1

platform: "SPR"


  
  
  
  
  
  
  
  

  
  
  
  
  

  
  
  
  
